apiVersion: v1
kind: Service
metadata:
  name: {{ include "restic.fullname" . }}
  labels:
    {{- include "restic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.monitor.service.type }}
  ports:
    - port: {{ .Values.monitor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "restic.selectorLabels" . | nindent 4 }}
