apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}      
      
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
